# Generated by Django 5.2.10 on 2026-01-29 14:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TableRestaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_table', models.CharField(max_length=10, unique=True, verbose_name='Numéro de table')),
                ('nombre_places', models.PositiveIntegerField(default=4, verbose_name='Nombre de places')),
                ('etat', models.CharField(choices=[('libre', 'Libre'), ('attente', 'Commande en attente'), ('servie', 'Commande servie'), ('payee', 'Commande payée')], default='libre', max_length=10, verbose_name='État')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('utilisateur', models.OneToOneField(limit_choices_to={'role': 'Rtable'}, on_delete=django.db.models.deletion.CASCADE, related_name='table_restaurant', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'Table',
                'verbose_name_plural': 'Tables',
                'ordering': ['numero_table'],
            },
        ),
    ]
